### ISSUE TITLE
kernel packages are not patched against rockchip vop2 & rga bugs

### ISSUE THREAD

**Issue by kyak** [7Ji-PKGBUILDs/.meta#31] opened 2024-03-16 15:52 UTC
It seems that `kodi-mpp-git` is not using the patch from [0001-windowing-gbm-Dynamic-plane-selection.patch](https://github.com/hbiyik/ffmpeg-rockchip/wiki/patches/kodi/0001-windowing-gbm-Dynamic-plane-selection.patch) : If not applied, video will be displayed on top of OSD when Kodi used in GBM mode.

https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#required-patches-and-fixes-in-the-toolchain

Can we please have this in the package?
Otherwise, kodi is more or less not usable in Direct-to-Plane mode (I have to switch to EGL).

**Comment by hbiyik** [comment] 2024-03-18 20:09
let me correct
kodi-mpp-git has this [patch](https://github.com/7Ji-PKGBUILDs/kodi-mpp-git/blob/master/0003-PR24431.patch),  and there is also a [PR](https://github.com/xbmc/xbmc/pull/24431) in xbmc.

The actual problem is kernel packages are not having the correct patchset.

Rockchip Linux
[0001-rga3_uncompact_fix.patch](https://github.com/hbiyik/ffmpeg-rockchip/wiki/patches/rockchip-kernel/0001-rga3_uncompact_fix.patch) : To get P010 & P210 support rockchip kernel must be fixed, if not the rendered picture will display broken
[0002-vop2_rbga2101010_capability_fix.patch](https://github.com/hbiyik/ffmpeg-rockchip/wiki/patches/rockchip-kernel/0002-vop2_rgba2101010_capability_fix.patch) : When using Kodi in GBM Mode, you will get a black screen if this patch is not applied. This is a bug in rockchip kernel.

kernel packages which has those pacthes
radxa-bsp5.10
joshua-bsp6.10

kernel packages has upstream PRs with the patches:
for joshua-bsp5.10 i have created a [PR](https://github.com/Joshua-Riek/linux-rockchip/pull/8)

but for opi5 people i have no clue how to handle, also i dont want to get personally involved, there are just too many entities maintaining the same thing....

**Comment by kyak** [comment] 2024-03-19 14:48
> but for opi5 people i have no clue how to handle, also i dont want to get personally involved, there are just too many entities maintaining the same thing....

I will try to apply these patches locally and report back.

@7Ji what would be the best way to have these patches included in `linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git`?

**Comment by kyak** [comment] 2024-03-19 19:13
> [0001-rga3_uncompact_fix.patch](https://github.com/hbiyik/ffmpeg-rockchip/wiki/patches/rockchip-kernel/0001-rga3_uncompact_fix.patch) : To get P010 & P210 support rockchip kernel must be fixed, if not the rendered picture will display broken
> [0002-vop2_rbga2101010_capability_fix.patch](https://github.com/hbiyik/ffmpeg-rockchip/wiki/patches/rockchip-kernel/0002-vop2_rgba2101010_capability_fix.patch) : When using Kodi in GBM Mode, you will get a black screen if this patch is not applied. This is a bug in rockchip kernel.

I've tried these patches locally with `linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git`. They solve the problem with OSD being drawn below the video in GDM mode with `kodi-mpp-git`.

**Comment by 7Ji** [comment] 2024-03-20 04:24
@kyak 
Sorry I'm busy with my job and other real-life businesses, and my focus for opi5 + desktop is no longer the opi vendor kernel, but rather Joshua's bsp 6.1, as opi is moving too slowly with their bsp6.1 (Currently I use Joshua bsp 6.1.43 on my 5 as desktop and OrangePi 5.10.160 on my 5 plus as server). 

If you're interested in improving the kernel you can either submit the patches to opi upstream, or/and fork the kernel package and add those patches locally and PR them back. If you're interested in multiple packages I could invite you to be a member of the 7Ji-PKGBUILDs org and let you modify them freely.

Or you can wait for me to implement those, but sadly this would not be on top of my to-do list, sorry.

**Comment by kyak** [comment] 2024-03-20 05:05
> (Currently I use Joshua bsp 6.1.43 on my 5 as desktop and OrangePi 5.10.160 on my 5 plus as server).

I would simply use that kernel, too. I'm all for focusing efforts, not spreading them.

Are there any downsides to using Joshua's bsp 6.1.43? Or, why do you still use 5.1.160 on your server?

**Comment by 7Ji** [comment] 2024-03-20 05:24
> Are there any downsides to using Joshua's bsp 6.1.43? Or, why do you still use 5.1.160 on your server?

Joshua's rk bsp 6.1 + booster as the initcpio generator instead of mkinitcpio would result in infinite error loop when booting on opi 5 plus and reporting a udev event it could not parse. This is probably caused by either some module being configured wrongly as =M instead of =Y, as booster is more strict on module loading, or booster lacking support for some devices of special types. This shouldn't happen if you use mkinitcpio.

**Comment by kyak** [comment] 2024-03-20 05:33
Thanks, I'll be using Joshua's rk bsp 6.1 then.

Maybe it makes sense to point https://github.com/7Ji/orangepi5-archlinuxarm users to use that kernel, too.

**Closed as completed** 2024-04-23 02:22 UTC
